# This workflow will publish an alpha or beta package tagged with "next" to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*-alpha*'
      - 'v*-beta*'


jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            args: [ --force ]

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          registry-url: https://registry.npmjs.org/
          scope: '@diamondlightsource'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish -r --no-git-checks --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_SCI_REACT_UI}}
