# This workflow will install dependencies, run tests and lint

name: Run CI

on:
  push:
    branches: [ "main" ]
    tags: ['v*']
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22.12.0"]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: pnpm/action-setup@v4
      with:
        run_install: |
          args: [ --force ]

    - name: Set Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm

    - name: Audit packages, run Typescript tests and lint client code
      run: |
        pnpm audit --prod --audit-level high
        pnpm lint
        pnpm jest
        pnpm build
